import "@fontsource-variable/montserrat"
import "@fontsource/merriweather"
import "@fontsource-variable/overpass-mono"
import "prismjs/themes/prism.css"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import "./src/styles/core.scss"
