import React, { useState, useEffect } from "react"
import PropTypes from "prop-types"

const REPORT_URL = "/lighthouse-report.json"
const FULL_REPORT_URL = "/lighthouse/report.html"

const GAUGE_SIZE = 108
const GAUGE_STROKE = 8
const GAUGE_RADIUS = (GAUGE_SIZE - GAUGE_STROKE) / 2
const GAUGE_CIRCUMFERENCE = 2 * Math.PI * GAUGE_RADIUS

// Same thresholds Lighthouse uses for its own gauges
const ratingOf = score =>
  score >= 0.9 ? "good" : score >= 0.5 ? "average" : "poor"

const Gauge = ({ title, score, animated }) => {
  const rating = ratingOf(score)
  const value = Math.round(score * 100)

  return (
    <div className={`page-speed-gauge page-speed-gauge--${rating}`}>
      <svg
        className="page-speed-gauge-svg"
        width={GAUGE_SIZE}
        height={GAUGE_SIZE}
        viewBox={`0 0 ${GAUGE_SIZE} ${GAUGE_SIZE}`}
        role="img"
        aria-label={`${title}: ${value} out of 100`}
      >
        <circle
          className="page-speed-gauge-track"
          cx={GAUGE_SIZE / 2}
          cy={GAUGE_SIZE / 2}
          r={GAUGE_RADIUS}
          strokeWidth={GAUGE_STROKE}
        />
        <circle
          className="page-speed-gauge-arc"
          cx={GAUGE_SIZE / 2}
          cy={GAUGE_SIZE / 2}
          r={GAUGE_RADIUS}
          strokeWidth={GAUGE_STROKE}
          strokeDasharray={GAUGE_CIRCUMFERENCE}
          strokeDashoffset={
            animated ? GAUGE_CIRCUMFERENCE * (1 - score) : GAUGE_CIRCUMFERENCE
          }
        />
      </svg>
      <span className="page-speed-gauge-value" aria-hidden="true">
        {value}
      </span>
      <span className="page-speed-gauge-title">{title}</span>
    </div>
  )
}

Gauge.propTypes = {
  title: PropTypes.string.isRequired,
  score: PropTypes.number.isRequired,
  animated: PropTypes.bool,
}

const PageSpeedInsight = () => {
  const [report, setReport] = useState(null)
  const [status, setStatus] = useState("loading")
  const [animated, setAnimated] = useState(false)

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const response = await fetch(`${REPORT_URL}?v=${Date.now()}`)
        if (!response.ok) throw new Error("Report not available")
        const data = await response.json()
        if (!data.categories?.length) throw new Error("Report is empty")
        setReport(data)
        setStatus("success")
      } catch (error) {
        setStatus("unavailable")
      }
    }

    fetchReport()
  }, [])

  // Let the arcs paint empty for one frame first so they animate into place
  useEffect(() => {
    if (!report) return undefined
    const frame = requestAnimationFrame(() =>
      requestAnimationFrame(() => setAnimated(true))
    )
    return () => cancelAnimationFrame(frame)
  }, [report])

  const auditedAt = report?.fetchTime
    ? new Date(report.fetchTime).toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      })
    : null

  return (
    <div className="page-speed section-surface px-4 py-5">
      <span className="section-eyebrow">Performance</span>
      <h4 className="text-center mt-0 mb-2">PageSpeed Insights</h4>
      <p className="lead text-center text-body-secondary mb-4">
        Generated by Google Lighthouse.
      </p>

      {status === "loading" && (
        <p className="text-center text-body-secondary mb-0">
          Loading latest report...
        </p>
      )}

      {status === "unavailable" && (
        <p className="text-center text-body-secondary mb-0">
          Scores are generated on every deploy and are not available in this
          build.
        </p>
      )}

      {status === "success" && (
        <>
          <div className="page-speed-gauges">
            {report.categories.map(category => (
              <Gauge
                key={category.id}
                title={category.title}
                score={category.score}
                animated={animated}
              />
            ))}
          </div>

          {report.metrics.length > 0 && (
            <ul className="list-unstyled page-speed-metrics">
              {report.metrics.map(metric => (
                <li
                  key={metric.id}
                  className={`page-speed-metric page-speed-metric--${ratingOf(
                    metric.score
                  )}`}
                >
                  <span className="page-speed-metric-label">
                    {metric.label}
                  </span>
                  <span className="page-speed-metric-value">
                    {metric.displayValue}
                  </span>
                </li>
              ))}
            </ul>
          )}

          <p className="page-speed-footnote">
            {auditedAt && <>Audited {auditedAt}</>}
            {report.formFactor && <> on {report.formFactor}</>}
            {report.lighthouseVersion && (
              <> with Lighthouse {report.lighthouseVersion}</>
            )}
            {". "}
            <a href={FULL_REPORT_URL} target="_blank" rel="noreferrer">
              View full report ↗
            </a>
          </p>
        </>
      )}
    </div>
  )
}

export default PageSpeedInsight
