import React, { useState, useEffect } from "react"
import PropTypes from "prop-types"

/**
 * PageSpeedInsight component
 * @param {Object} scores - object containing lighthouse scores
 * @returns {ReactElement} - PageSpeedInsight component
 */
const PageSpeedInsight = () => {
  const [data, setData] = useState({})

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        `lighthouse-report.json?v=${new Date().getTime()}`,
        {
          mode: "no-cors",
        }
      )
      const data = await response.json()
      setData(data)
    }
    fetchData()
  }, [])

  const scoreColor = score => {
    if (score >= 0.75) return "page-speed-score--good"
    if (score >= 0.5) return "page-speed-score--fair"
    return "page-speed-score--poor"
  }

  return (
    <div className="page-speed section-surface px-4 py-5">
      <span className="section-eyebrow">Performance</span>
      <h4 className="text-center mt-0 mb-2">PageSpeed Insights</h4>
      <p className="lead text-center text-body-secondary mb-4">
        Generated by Google Lighthouse.
      </p>
      <ul className="list-unstyled page-speed-list">
        {Object.keys(data?.categories || {}).map(key => (
          <li
            key={key}
            className={`page-speed-tile ${scoreColor(
              data.categories[key].score
            )}`}
          >
            <span className="page-speed-key">{key}</span>
            <span className="page-speed-value">
              {data.categories[key].score * 100}
            </span>
          </li>
        ))}
      </ul>
    </div>
  )
}

PageSpeedInsight.propTypes = {
  scores: PropTypes.object,
}

export default PageSpeedInsight
