import React, { useState, useEffect } from "react"
import PropTypes from "prop-types"

/**
 * PageSpeedInsight component
 * @param {Object} scores - object containing lighthouse scores
 * @returns {ReactElement} - PageSpeedInsight component
 */
const PageSpeedInsight = () => {
  const [data, setData] = useState({})

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(`report.json?v=${new Date().getTime()}`, {
        mode: "no-cors",
      })
      const data = await response.json()
      setData(data)
    }
    fetchData()
  }, [])

  return (
    <div className="page-speed">
      <h4 className="mt-5">PageSpeed Insights</h4>
      <p className="text-muted">
        This site is generated by PageSpeed Insights (PSI) Lighthouse
      </p>
      <ul className="list-unstyled">
        {Object.keys(data?.categories || {}).map(key => (
          <li
            key={key}
            style={{
              display: "inline-block",
              margin: "5px",
              border: "1px solid #ccc",
              padding: "10px",
              borderRadius: "5px",
            }}
          >
            <strong>{key}</strong>:
            <span
              style={{
                color:
                  data.categories[key].score >= 0.75
                    ? "green"
                    : data.categories[key].score >= 0.5
                    ? "orange"
                    : "red",
              }}
            >
              {data.categories[key].score * 100}
            </span>
          </li>
        ))}
      </ul>
    </div>
  )
}

PageSpeedInsight.propTypes = {
  scores: PropTypes.object,
}

export default PageSpeedInsight
